from .settings import (
    Settings, get_settings, DEPARA_FILIAIS, TABELA_DEPARA_TIPODOC,
    TIPO_DOC_POR_EMITENTE, CNPJ_ALUGUEL_IR, CNPJ_VIBRA_ENERGIA, COND_PAGTO_A_VISTA, TIPOS_DOC_SERVICO,
)
__all__ = [
    "Settings", "get_settings", "DEPARA_FILIAIS", "TABELA_DEPARA_TIPODOC",
    "TIPO_DOC_POR_EMITENTE", "CNPJ_ALUGUEL_IR", "CNPJ_VIBRA_ENERGIA", "COND_PAGTO_A_VISTA", "TIPOS_DOC_SERVICO",
]
