from .settings import (
    Settings, get_settings, DEPARA_FILIAIS, TABELA_DEPARA_TIPODOC,
    TIPO_DOC_POR_EMITENTE, CNPJ_ALUGUEL_IR, CNPJ_VIBRA_ENERGIA, CNPJ_APLICACAO_281,
    CNPJ_EQUATORIAL, COND_PAGTO_A_VISTA, TIPOS_DOC_SERVICO, ALMOXARIFADO_LOCALIZACAO,
    FANTASIAS_EXECUCAO_MANUAL, CNPJ_CORRETO_POR_FANTASIA, CNPJ_TOMADOR_CORRETO_POR_FANTASIA,
    ARQUIVOS_PROTEGIDOS_SENHA, FANTASIAS_PROVAVEL_SENHA, FANTASIAS_MODEL_TIER_ALTO,
)
__all__ = [
    "Settings", "get_settings", "DEPARA_FILIAIS", "TABELA_DEPARA_TIPODOC",
    "TIPO_DOC_POR_EMITENTE", "CNPJ_ALUGUEL_IR", "CNPJ_VIBRA_ENERGIA", "CNPJ_APLICACAO_281",
    "CNPJ_EQUATORIAL", "COND_PAGTO_A_VISTA", "TIPOS_DOC_SERVICO", "ALMOXARIFADO_LOCALIZACAO",
    "FANTASIAS_EXECUCAO_MANUAL", "CNPJ_CORRETO_POR_FANTASIA", "CNPJ_TOMADOR_CORRETO_POR_FANTASIA",
    "ARQUIVOS_PROTEGIDOS_SENHA", "FANTASIAS_PROVAVEL_SENHA",
    "FANTASIAS_MODEL_TIER_ALTO",
]
